'use client'

import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import 'remixicon/fonts/remixicon.css'
import { QueryClient, QueryClientProvider, useQuery } from 'react-query'
import getAwsAuthCredetial from '@/services/get-aws-credentials'

const Jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
})

// export const metadata = {
//   title: 'PASS',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  // getAwsAuthCredetial()
  const queryClient = new QueryClient()

  return (
    <html lang='en'>
      <body className={Jakarta.className} suppressHydrationWarning={true}>
        <QueryClientProvider client={queryClient}>
          <Toaster toastOptions={{ className: 'toast-container' }} />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}

