"use client"

import MobileNavBar from '@/components/navbars/mobile-navbar'
import Navbar from '@/components/navbars/navbar'
import SideNavbar from '@/components/navbars/side-navbar'
import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'
// export const metadata = {
//   title: 'PASS | Bids',
//   description: 'Generated by create next app',
// }

export default function AuthLayout({ children }) {
    const router = useRouter()
    const [isValid, setIsValid] = useState(false)
    const [currentPath, setCurrentPath] = useState({})

    // const details = [{
    //     pathname: "/home",
    //     titleName: "Home",
    //     isForRevert: false
    // },

    // {
    //     pathname: "/start-bid",
    //     titleName: "Bid",
    //     isForRevert: true,
    //     revertPath: "/home"
    // },
    // {
    //     pathname: "/bids",
    //     titleName: "Bids List",
    //     isForRevert: true,
    //     revertPath: "/home"
    // },
    // {
    //     pathname: "/bid-details",
    //     titleName: "Bids Details",
    //     isForRevert: true,
    //     revertPath: "/bids"
    // },
    // {
    //     pathname: "/reports",
    //     titleName: "Reports",
    //     isForRevert: false,
    // },
    // {
    //     pathname: "/reports/day-wise",
    //     titleName: "Reports List",
    //     isForRevert: true,
    //     revertPath: "/reports"
    // },
    // {
    //     pathname: "/reports/moth-wise",
    //     titleName: "Reports List",
    //     isForRevert: true,
    //     revertPath: "/reports"
    // },
    // ]
    // const currentPathName = usePathname()

    // useEffect(() => {
    //     console.log("path", currentPathName);

    // }, [])






    return (
        <>
            {/* {isValid && */}
            {/* <> */}

            <div className='hidden bigTablet:block'>
                <SideNavbar />
                <Navbar />
            </div>

            {/* <div className='block bigTablet:hidden'>
                <MobileNavBar />
            </div> */}

            {children}
            {/* </> */}

            {/* } */}
        </>
    )
}
